---
title: "Week 8: Quiz"
author: "Your name"
date:  "`r Sys.Date()`"
output:
  html_document:
    theme: cerulean
    highlight: tango
    toc: true
    toc_depth: 3
    toc_float: true
    self_contained: true
---
<style>

table, td, th {
  border: none;
  padding-left: 1em;
  padding-right: 1em;
  min-width: 50%;
  margin-left: auto;
  margin-right: auto;
  margin-top: 1em;
  margin-bottom: 1em;
}

</style>

```{css, echo=F}
.kakomi-box11 {
 position: relative;
 margin: 2em auto;
 padding: 1.2em;
 color: #555555; /* 文章色 */
 background-color: #fff; /* 背景色 */
 border: 1px solid #555555; /* 枠線の太さ - 色 */
 width: 90%;
}
.title-box11 {
 position: absolute;
 padding: 0 .5em;
 left: 20px;
 top: -15px;
 font-weight: bold;
 background-color: #fff; /* タイトル背景色 */
 color: #555555; /* タイトル文字色 */
}
```

```{r, include = FALSE}
knitr::opts_chunk$set(
  warning = FALSE,       
  message = FALSE,      
  comment = "",
  fig.align = "center"  
  )
```

# 5. 練習問題  
- 衆院選挙データ (`hr96-21.csv`) を使って次の問題に答えなさい　　

#### Q5.1:  
- `group_by()` 関数と `ggplot()` 関数を使って総選挙 (1996-2021) の立候補者の平均年齢をすべての政党ごとに計算し線グラフで可視化しなさい  



#### Q5.2:  
- 政党を自民党、民主党、公明党に絞って表示しなさい




#### Q5.3:  
- 総選挙 (1996-2021) の当選者の平均年齢を 3 つの政党（自民党、民主党、公明党）ごとに計算し線グラフで可視化しなさい。その際、当選者の数も表示すること。  



#### Q5.4    

- 変数 `wl` の値は 0, 1, 2 の 3 つである  

| 変数名        | 詳細 |
|:---------------|:-----------------------|
| wl |選挙の当落: 1 = 小選挙区当選、2 = 復活当選、0 = 落選|
|     |    |

- `if_else()` 関数を使って、小選挙区で当選した候補者を 1、小選挙区で落選した候補者を 0 とした小選挙区当選ダミー (`wlsmd`) を作成しなさい

- `table()` 関数と `unique()` 関数を使って、変数 `wlsmd` が正しく作成されたかどうかチェックしなさい    



##### Q5.5  
- `filter()` 関数を使って2021年総選挙だけのデータを抜き出し、`if_else()` 関数を使って、自民党候補者を 1、それ以外の候補者を 0 とした自民党ダミー (`ldp`) を作成しなさい  

- `table()` 関数と `unique()` 関数を使って、変数 `ldp` が正しく作成されたかどうかチェックしなさい


##### Q5.6  
- `filter()` 関数を使って2021年総選挙だけのデータを抜き出し、`mutate()` 関数、`if_else()` 関数、`%in%` 関数、`group_by()` 関数を使って、政権与党（自民党と公明党の合計）と野党候補者の平均年齢を比較して表示しなさい  
- その際、政権与党と野党それぞれの候補者人数も表示しなさい  


##### Q5.7  
- `filter()` 関数を使って2021年総選挙だけのデータを抜き出し、`mutate()` 関数、`if_else()` 関数、`%in%` 関数、`group_by()` 関数を使って、政権与党（自民党と公明党の合計）と野党の**[当選者（比例復活当選者含む）]{style="color:red"}**の平均年齢を比較して表示しなさい  
- その際、政権与党と野党それぞれの候補者人数も表示しなさい  


##### Q5.8    
- `filter()` 関数を使って2021年総選挙だけのデータを抜き出し、`mutate()` 関数、`case_when()` 関数と `group_by()` 関数を使って、自民党、公明党、立憲民主党、立憲民主党以外の野党の**[当選者（比例復活当選者含む）]{style="color:red"}**の平均年齢を比較して表示しなさい  
- その際、自民党、公明党、立憲民主党、野党それぞれの候補者人数も表示しなさい  





