---
title: "Week 11: 問題"
author: "Your name"
date:  "`r Sys.Date()`"
output:
  html_document:
    theme: journal
    highlight: tango
    toc: true
    toc_depth: 3
    toc_float: true
    self_contained: true
---

<style>

table, td, th {
  border: none;
  padding-left: 1em;
  padding-right: 1em;
  min-width: 50%;
  margin-left: auto;
  margin-right: auto;
  margin-top: 1em;
  margin-bottom: 1em;
}

</style>

```{css, echo=F}
.kakomi-box11 {
 position: relative;
 margin: 2em auto;
 padding: 1.2em;
 color: #555555; /* 文章色 */
 background-color: #fff; /* 背景色 */
 border: 1px solid #555555; /* 枠線の太さ - 色 */
 width: 90%;
}
.title-box11 {
 position: absolute;
 padding: 0 .5em;
 left: 20px;
 top: -15px;
 font-weight: bold;
 background-color: #fff; /* タイトル背景色 */
 color: #555555; /* タイトル文字色 */
}
```

```{r, include = FALSE}
knitr::opts_chunk$set(
  warning = FALSE,       
  message = FALSE,      
  comment = "",
  fig.align = "center"  
  )
```  

### 4. Exercise     
- [`hr96-21.csv`](http://www.ner.takushoku-u.ac.jp/masano/class_material/waseda/keiryo/Data/hr96-21.csv)  は1996年に衆院選挙に小選挙区が導入されて以来実施された 9  回の衆議院選挙（1996, 2000, 2003, 2005, 2009, 2012, 2014, 2017, 2021）の結果のデータ    
- このデータの中から2005年の衆議院選挙データだけ取り出し、次の 3 つの変数 (`voteshare`, `exppv`, `jcp`) を使って重回帰分析を行いなさい  

|変数の種類|変数名|詳細|
|:--|:--|:---------------|
|応答変数|`voteshare`|得票率 (%)|
|説明変数|`exppv`|有権者一人当たりに候補者が費やした選挙費用（円）|
|制御変数|`jcp`|共産党ダミー（共産党候補者 = 1、それ以外 = 0）|
|||  

**注意：`jcp ダミー`は自分で作成すること**  

#### Q1:  
- `stargazer()`を使って、2005年の衆議院選挙の 3 つの変数 (`voteshare`, `exppv`, `jcp`) の記述統計を表示させなさい  

#### Q2:   
- `exppv` と `voteshare` の散布図を描きなさい  その際、回帰直線も表示すること    

#### Q3:  
- `jcp` と `voteshare` の散布図を描きなさい  その際、回帰直線も表示すること    

#### Q4:  
- `voteshare` を応答変数、`exppv` と `jcp` を説明変数とした重回帰分析を実行し、その重回帰式を示し、重回帰分析結果を解釈しなさい  

#### Q5:  
- `voteshare` を応答変数、`exppv` と `jcp` を説明変数とした散布図を描きなさい  その際、観測値と回帰直線はダミー変数 (`jcp`) で色分けすること  
（白黒で描く場合には、散布図のドットの形を変えたり、回帰直線の種類を 2 種類使うこと）

